// Mapa de imágenes de cartas (require estático, necesario para Metro).
// Mismas cartas que usa el póker: clave 'Palo-Valor' (ej. 'S-A', 'H-10').

export const CARTAS_IMG: Record<string, any> = {
  'BACK': require('../../assets/póker-assets/BACK.png'),
  'S-A':  require('../../assets/póker-assets/S-A.png'),
  'S-2':  require('../../assets/póker-assets/S-2.png'),
  'S-3':  require('../../assets/póker-assets/S-3.png'),
  'S-4':  require('../../assets/póker-assets/S-4.png'),
  'S-5':  require('../../assets/póker-assets/S-5.png'),
  'S-6':  require('../../assets/póker-assets/S-6.png'),
  'S-7':  require('../../assets/póker-assets/S-7.png'),
  'S-8':  require('../../assets/póker-assets/S-8.png'),
  'S-9':  require('../../assets/póker-assets/S-9.png'),
  'S-10': require('../../assets/póker-assets/S-10.png'),
  'S-J':  require('../../assets/póker-assets/S-J.png'),
  'S-Q':  require('../../assets/póker-assets/S-Q.png'),
  'S-K':  require('../../assets/póker-assets/S-K.png'),
  'H-A':  require('../../assets/póker-assets/H-A.png'),
  'H-2':  require('../../assets/póker-assets/H-2.png'),
  'H-3':  require('../../assets/póker-assets/H-3.png'),
  'H-4':  require('../../assets/póker-assets/H-4.png'),
  'H-5':  require('../../assets/póker-assets/H-5.png'),
  'H-6':  require('../../assets/póker-assets/H-6.png'),
  'H-7':  require('../../assets/póker-assets/H-7.png'),
  'H-8':  require('../../assets/póker-assets/H-8.png'),
  'H-9':  require('../../assets/póker-assets/H-9.png'),
  'H-10': require('../../assets/póker-assets/H-10.png'),
  'H-J':  require('../../assets/póker-assets/H-J.png'),
  'H-Q':  require('../../assets/póker-assets/H-Q.png'),
  'H-K':  require('../../assets/póker-assets/H-K.png'),
  'D-A':  require('../../assets/póker-assets/D-A.png'),
  'D-2':  require('../../assets/póker-assets/D-2.png'),
  'D-3':  require('../../assets/póker-assets/D-3.png'),
  'D-4':  require('../../assets/póker-assets/D-4.png'),
  'D-5':  require('../../assets/póker-assets/D-5.png'),
  'D-6':  require('../../assets/póker-assets/D-6.png'),
  'D-7':  require('../../assets/póker-assets/D-7.png'),
  'D-8':  require('../../assets/póker-assets/D-8.png'),
  'D-9':  require('../../assets/póker-assets/D-9.png'),
  'D-10': require('../../assets/póker-assets/D-10.png'),
  'D-J':  require('../../assets/póker-assets/D-J.png'),
  'D-Q':  require('../../assets/póker-assets/D-Q.png'),
  'D-K':  require('../../assets/póker-assets/D-K.png'),
  'C-A':  require('../../assets/póker-assets/C-A.png'),
  'C-2':  require('../../assets/póker-assets/C-2.png'),
  'C-3':  require('../../assets/póker-assets/C-3.png'),
  'C-4':  require('../../assets/póker-assets/C-4.png'),
  'C-5':  require('../../assets/póker-assets/C-5.png'),
  'C-6':  require('../../assets/póker-assets/C-6.png'),
  'C-7':  require('../../assets/póker-assets/C-7.png'),
  'C-8':  require('../../assets/póker-assets/C-8.png'),
  'C-9':  require('../../assets/póker-assets/C-9.png'),
  'C-10': require('../../assets/póker-assets/C-10.png'),
  'C-J':  require('../../assets/póker-assets/C-J.png'),
  'C-Q':  require('../../assets/póker-assets/C-Q.png'),
  'C-K':  require('../../assets/póker-assets/C-K.png'),
}

export const MESA_IMG = require('../../assets/póker-assets/table.png')
